名字: 同步Garmin Global到Garmin CN

在:
  workflow_dispatch:
时间表:
    #  每1小时检查一次
    - cron（通常读作“克朗”）是一个用于: "0 * * * *"

环境:
  #请更改为自己的配置。
  RQ_COOKIE: ${{ secrets.RQ_COOKIE }}
  RQ_CSRF_TOKEN: ${{ secrets.RQ_CSRF_TOKEN }}
  RQ_USERID: ${{ secrets.RQ_USERID }}
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_API_CLIENT_EMAIL: ${{ secrets.GOOGLE_API_CLIENT_EMAIL }}
  GOOGLE_API_PRIVATE_KEY: ${{ secrets.GOOGLE_API_PRIVATE_KEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
  GARMIN_GLOBAL_USERNAME: ${{ secrets.GARMIN_GLOBAL_USERNAME }}
  GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}

工作:
建筑:
    runs-on: ubuntu-latest
名字: 同步Garmin Global到Garmin CN
权限:
内容: 写
步骤:
      - 用途: actions/checkout@v3
      - 用途: actions/setup-node@v3
与:
          node-version: "18"
贮存物: "yarn"
跑用途纱线 sync_global: 与
      - 跑: 纱线 sync_global
        timeout-minutes: 5
      - 跑: stefanzweifel/git-auto-commit-action@v5
纱:
          commit_message: 保存Garmin会话
